
# JWT Configuration
jwt:
  secret: 2?Q:mba;7mvN[^0=Ixw54z@YOiySC!TqGF)-20tOL`*qs^AlK_|gYoS;ah0r2Oj
  expiration: 86_400_000 # 24 hours
  issuer: 'Obsidi Academy'
  audience: WeatherApp
  prefix: 'Bearer '
  excluded.urls: > 
    /user/login,
    /user/signup,
    /user/reset/*,
    /test/**,
    /actuator/**,
    /error
    
# Open Weather API Configuration  
api:
  key: 7874e22d1973fbd321f5be2a6a514218
  base:
    url: https://api.openweathermap.org/data/2.5/weather

# Client Configuration  
client:
  url: http://localhost:3000
  email:
    verify: 
      param: verify
      expiration: 86_400_000 # 24 hours
    reset: 
      param: reset
      expiration: 86_400_000 # 24 hours 

# H2 Server Configuration 
h2.server:
  params: >
    -tcp, 
    -tcpAllowOthers, 
    -tcpPort, 
    9091